### ISSUE TITLE
Cannot start viewer on Raspberry Pi Zero 2 W

### ISSUE THREAD

**Issue by ClintHaerinck** [Screenly/Anthias#1573]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

When starting viewer:
```
 srly-ose-viewer  Traceback (most recent call last):
 srly-ose-viewer    File "viewer.py", line 50, in <module>
 srly-ose-viewer      media_player = VLCMediaPlayer() if get_raspberry_model(get_raspberry_code()) == 'Model 4B' else OMXMediaPlayer()
 srly-ose-viewer    File "/usr/src/app/lib/diagnostics.py", line 128, in get_raspberry_model
 srly-ose-viewer      return raspberry_pi_helper.lookup_raspberry_pi_revision(raspberry_pi_revision)['model']
 srly-ose-viewer  TypeError: string indices must be integers, not str
 srly-ose-viewer  ./bin/start_viewer.sh: line 47: kill: (38) - No such process
```

#### Reproduction Steps

Add device type to `raspberrypi0-2w-64` to balena.yml. Push application to device.

#### Environment

* Raspberry Pi Hardware Version: Raspberry Pi Zero 2 W
* Raspberry Pi Network Setup: USB Ethernet Dongle
* Screenly OSE Version: @

**Comment by semaf** [comment]
Seems same issue like here https://github.com/Screenly/screenly-ose/issues/1571

**Comment by vpetersson** [comment]
`OMXMediaPlayer` and the old `lib/diagnostics.py` revision-lookup helper are both gone from the current codebase. Pi Zero 2 W is also outside our supported board matrix. Closing.
