### ISSUE TITLE
Issue with Boot

### ISSUE THREAD

**Issue by vpetersson** [Screenly/Anthias#1745]
We've had multiple reports of balenaOS not booting properly.

I've reproduced this myself now both using the official image, as well as a developer image on the fleet.

Here's the error:

```
 srly-ose-viewer  Traceback (most recent call last):
 srly-ose-viewer    File "viewer.py", line 20, in <module>
 srly-ose-viewer      import zmq
 srly-ose-viewer    File "/usr/local/lib/python2.7/dist-packages/zmq/__init__.py", line 50, in <module>
 srly-ose-viewer      from zmq import backend
 srly-ose-viewer    File "/usr/local/lib/python2.7/dist-packages/zmq/backend/__init__.py", line 40, in <module>
 srly-ose-viewer      reraise(*exc_info)
 srly-ose-viewer    File "/usr/local/lib/python2.7/dist-packages/zmq/backend/__init__.py", line 27, in <module>
 srly-ose-viewer      _ns = select_backend(first)
 srly-ose-viewer    File "/usr/local/lib/python2.7/dist-packages/zmq/backend/select.py", line 28, in select_backend
 srly-ose-viewer      mod = __import__(name, fromlist=public_api)
 srly-ose-viewer    File "/usr/local/lib/python2.7/dist-packages/zmq/backend/cython/__init__.py", line 6, in <module>
 srly-ose-viewer      from . import (constants, error, message, context,
 srly-ose-viewer  ImportError: libzmq.so.5: cannot open shared object file: No such file or directory
 srly-ose-viewer  ./bin/start_viewer.sh: line 57: kill: (38) - No such process
```

**Comment by vpetersson** [comment]
Just FYI -- i tried debugging this using a serial console on a Raspberry Pi 4, but even with the 'developer image' from Balena, i wasn't able to get any debug logging.

**Comment by vpetersson** [comment]
This should be closed now.
