### ISSUE TITLE
Error while running Anthias to Screenly migration Script

### ISSUE THREAD

**Issue by salmanfarisvp** [Screenly/Anthias#1846]
#### Overview of the Issue

Unexpected errors while trying to migrate Anthias to Screenly using the provided Python script. 

#### Reproduction Steps

* Install and Setup Anthias on a Pi
* Install the required Python lib by `pip install click==8.1.7 requests==2.31.0 sh==2.0.6`
* Copy Anthias API Code 
* SSH to Pi and run command to start migration `python screenly/tools/assets-migration-to-screenly-pro.py`
* 
```

pi@raspberrypi:~ $ python screenly/tools/assets-migration-to-screenly-pro.py

       _____                           __         ____  _____ ______
      / ___/_____________  ___  ____  / /_  __   / __ \/ ___// ____/
      \__ \/ ___/ ___/ _ \/ _ \/ __ \/ / / / /  / / / /\__ \/ __/
     ___/ / /__/ /  /  __/  __/ / / / / /_/ /  / /_/ /___/ / /___
    /____/\___/_/   \___/\___/_/ /_/_/\__, /   \____//____/_____/
                                     /____/

What do you want to use for migration?
1.API token
2.Credentials
0.Exit
Your choice (1, 2, 0): 1
Your API key: XXXXXXXXXXXXX
Successfull authentication
Do you want to start assets migration? [y/N]: y


Ngrok starting ...
Ngrok successfull started
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x75c3dfd0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4040): Max retries exceeded with url: /api/tunnels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x75c3dfd0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/screenly/tools/assets-migration-to-screenly-pro.py", line 201, in main
    start_migration()
  File "/home/pi/screenly/tools/assets-migration-to-screenly-pro.py", line 161, in start_migration
    set_ngrok_public_url(get_ngrock_public_url())
  File "/home/pi/screenly/tools/assets-migration-to-screenly-pro.py", line 56, in get_ngrock_public_url
    response = requests.get('http://127.0.0.1:%i/api/tunnels' % PORT_NGROK, timeout=10).json()
  File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4040): Max retries exceeded with url: /api/tunnels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x75c3dfd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

#### Environment

* Raspberry Pi Hardware Version: Raspberry Pi 3 Model B Rev 1.2
* Rasberry Pi OS: Raspberry PI Bulleseye 64-bit 
* Raspberry Pi Network Setup: Ethernet and WiFi 
* Anthias Version: master@4170486

**Comment by nicomiguelino** [comment]
@salmanfarisvp, you can now test the changes in #1932.

#### Preparation

- Prepare your Screenly account. Make sure that you have your API key handy when prompted.
- Ensure that you have an Anthias installed on a Raspberry Pi OS (preferrably Bookworm).
  - Make sure that it's SSH-able.

#### Switching to the PR branch

```bash
git remote add nico https://github.com/nicomiguelino/Anthias.git
git fetch nico
git checkout fix-anthias-to-screenly-migration-script
```

#### Running the migration script

Check [this section of README.md](https://github.com/nicomiguelino/Anthias/blob/fix-anthias-to-screenly-migration-script/README.md#migrating-assets-from-anthias-to-screenly) for details.
